micronaut:
  application:
    name: micronautIntro

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/tdc
    driverClassName: org.postgresql.Driver
    username: postgres
    password: changeme
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true
